services:

  mysql:
    image: mysql:8.0
    container_name: todo-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: todo_db

    ports:
      - "3316:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: